server:
  port: 8080
  servlet:
    context-path: /bb
spring:
  jdbc:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot-test
      username: test
      password: test